#!/usr/bin/env node
/* Vercel build step.
 *
 * Reads runtime env vars and writes src/env.js with a small
 * window.CARBONCHIP_ENV object the browser-side code can consume.
 *
 * Safe to run anywhere — missing vars become empty strings, and the
 * Quote Builder falls back to its in-browser API-key modal.
 */
const fs = require('fs');
const path = require('path');

const mapsKey =
  process.env.GOOGLEMAPS_API ||
  process.env.GOOGLE_MAPS_API_KEY ||
  process.env.NEXT_PUBLIC_GOOGLE_MAPS_API ||
  '';

const content = `// AUTO-GENERATED by build.js at deploy time. Do NOT edit by hand.
// Local dev: this file ships with empty values; the UI falls back to a
// per-browser localStorage key set via the "Set Maps key" modal.
window.CARBONCHIP_ENV = {
  mapsKey: ${JSON.stringify(mapsKey)},
  builtAt: ${JSON.stringify(new Date().toISOString())},
};
`;

const outPath = path.join(__dirname, 'src', 'env.js');
fs.writeFileSync(outPath, content);

// Truncated key in build log to make leaks via public build logs harder.
// Just print a yes/no instead of any portion of the key.
console.log(`[build] Wrote ${outPath} — mapsKey: ${mapsKey ? 'set' : 'unset'}`);
console.log(`[build] ANTHROPIC_API_KEY: ${process.env.ANTHROPIC_API_KEY ? 'set (server-only)' : 'unset — /api/chat will 500'}`);
