// AUTO-GENERATED by build.js at deploy time. Do NOT edit by hand.
// Local dev: this file ships with empty values; the UI falls back to a
// per-browser localStorage key set via the "Set Maps key" modal.
window.CARBONCHIP_ENV = {
  mapsKey: "",
  builtAt: "",
};
